[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Default Netlify Function timeout is 10s on free, 26s on Pro.
  # We'll keep individual functions short and orchestrate from the client.
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
